# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34c79828de533973d3d57c337c000f212b455191ac24670c827e46e1a3d9f1ae00048eed2631a17859dbd93b740940f0c0f932f4dba39a0c053e39e4063c1f7

test:
  secret_key_base: ab23a953554298de898e888ce3df3b4f51476a7692683e10ef8aecc9cd72965aa4d5826bc1c36f45683093df5a61bbc4106a42dfd9727641893d53cb9005c651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
